# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto 0
__all__ = ['map']

# %% ../nbs/index.ipynb 2
from . import datacube_tools, interactive, setup, invert, regression

# %% ../nbs/index.ipynb 3
from oggm import cfg, utils, graphics

# %% ../nbs/index.ipynb 10
map = interactive.Widget()

# %% ../nbs/index.ipynb 11
map.display()
