# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_GPregression.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/05_GPregression.ipynb 3
from . import datacube_tools, setup, interactive

# %% ../nbs/05_GPregression.ipynb 4
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, WhiteKernel, ConstantKernel, ExpSineSquared, RationalQuadratic, RBF
from sklearn.model_selection import GridSearchCV
#from skopt import BayesSearchCV
#from skopt.space import Real, Categorical, Integer
#from sklearn.pipeline import Pipeline

# %% ../nbs/05_GPregression.ipynb 7
try:
    coords, gpdf, urls = interactive.return_clicked_info(data_map)
    point = [coords[0][1], coords[0][0]]
except:
    pass
