# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_temporalbaseline_filter.ipynb.

# %% auto 0
__all__ = ['swap_time_dim']

# %% ../nbs/06_temporalbaseline_filter.ipynb 4
from . import datacube_tools, interactive, obj_setup

# %% ../nbs/06_temporalbaseline_filter.ipynb 5
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from scipy.interpolate import CubicSpline

# %% ../nbs/06_temporalbaseline_filter.ipynb 13
def swap_time_dim(ds):
    ds['time_numeric'] = ds.mid_date.dt.year + ds.mid_date.dt.dayofyear / 365
    ds = ds.swap_dims({'mid_date':'time_numeric'})

    ds['img1_numeric'] = ds.acquisition_date_img1.dt.year + ds.acquisition_date_img1.dt.dayofyear / 365
    ds['img2_numeric'] = ds.acquisition_date_img2.dt.year + ds.acquisition_date_img2.dt.dayofyear / 365
    return ds#| export

