# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_GPregression.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/04_GPregression.ipynb 3
from . import access, setup

# %% ../nbs/04_GPregression.ipynb 4
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, WhiteKernel, ConstantKernel, ExpSineSquared, RationalQuadratic, RBF
from sklearn.model_selection import GridSearchCV
#from skopt import BayesSearchCV
#from skopt.space import Real, Categorical, Integer
#from sklearn.pipeline import Pipeline
